from . import ir_attachment
from . import ir_http
from . import boq_submission
from . import approval_request
from . import crm_extension
from . import department
from . import hr_employee_extension
from . import mail_activity
from . import mail_activity_guard
from . import payslip_extension
from . import project_email
from . import project_extension
from . import purchase_order_extension
from . import rule_step
from . import res_users  # <--- MAKE SURE THIS LINE EXISTS
from . import fix_project_task
from . import tender
from . import tender_controller
from . import project_project
from . import project_ai_manager
from . import ai_dashboard_tile