from odoo import models, fields, api

# 1. Define Category Model
class ProjectEmailCategory(models.Model):
    _name = "project.email.category"
    _description = "Email Category"
    name = fields.Char(required=True)
    color = fields.Integer(string="Color Index")

# 2. Define Project Email Model
class ProjectEmail(models.Model):
    _name = "project.email"
    _description = "Project Email"
    _order = "date desc"

    project_id = fields.Many2one("project.project", ondelete="cascade", required=True)
    
    subject = fields.Char(readonly=True)
    email_from = fields.Char(string="From", readonly=True)
    email_to = fields.Char(string="To", readonly=True)
    date = fields.Datetime(readonly=True)
    
    preview = fields.Text(string="Preview", readonly=True)
    body_html = fields.Html(string="Full Email Body", readonly=True, sanitize=True)
    
    attachment_ids = fields.Many2many("ir.attachment", string="Attachments", readonly=True, bypass_search_access=True)
    category_id = fields.Many2one("project.email.category", string="Categories")

    # UPDATED: Added Old Contractor/Consultant folders
    folder = fields.Selection([
        ('main', 'Others (Authorities)'),
        ('owner', 'Owner'),
        ('consultant', 'Consultant'),
        ('contractor', 'Contractor'),
        ('internal', 'Internal / Team'),
        ('old_consultant', 'Old Consultant'),  # New
        ('old_contractor', 'Old Contractor')   # New
    ], string="Folder", default='main')

    @api.model
    def check_access_rights(self, operation, raise_exception=True):
        # This ensures the system doesn't block the basic loading of the model
        return super(ProjectEmail, self).check_access_rights(operation, raise_exception=raise_exception)

# 3. PROJECT MODEL
class Project(models.Model):
    _inherit = "project.project"

    # ... (Previous fields) ...
    x_studio_offical_email = fields.Char(string="Owner Email")
    x_studio_consultant_email = fields.Char(string="Consultant Email")
    x_studio_contractor_email = fields.Char(string="Contractor Email")
    x_studio_consultant = fields.Char(string="Consultant Name")
    
    # === NEW FIELDS FOR OLD CONTACTS ===
    # These match the names usually generated by Studio or manual addition
    x_studio_old_consultant_email = fields.Char(string="Old Consultant Email")
    x_studio_old_contractor_email = fields.Char(string="Old Contractor Email")
    # ===================================

    email_ids = fields.One2many("project.email", "project_id", string="Emails")
    email_count = fields.Integer(compute='_compute_email_count', string="Email Count")

    @api.depends('email_ids')
    def _compute_email_count(self):
        for record in self:
            record.email_count = len(record.email_ids)

    def action_open_project_emails(self):
        self.ensure_one()
        return {
            'name': 'Project Emails',
            'type': 'ir.actions.act_window',
            'res_model': 'project.email',
            'view_mode': 'list,form',
            'domain': [('project_id', '=', self.id)],
            'context': {'default_project_id': self.id},
            'help': '<p class="o_view_nocontent_smiling_face">No emails found.</p>'
        }